#!/bin/zsh

# swap capslock with escape
if test $(uname) = Linux && test ! -z "$DISPLAY"; then
	setxkbmap -option caps:swapescape
fi

# Environment
export COLORTERM=truecolor
export EDITOR=vi

# brew
if test $(uname) = "Darwin"; then
	eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# go
export PATH="$PATH:/usr/local/go/bin"
export PATH="$PATH:$HOME/go/bin"

# python
export PATH="$HOME/.local/bin:$PATH"

# rust
. "$HOME/.cargo/env"
export PATH="$PATH:$HOME/.local/share/bob/nvim-bin"

# prompt
if test "$SHELL" = /bin/zsh; then
	eval "$(starship init zsh)"
else
	eval "$(starship init bash)"
fi

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# tat: tmux attach
function tat {
  name=$(basename `pwd` | sed -e 's/\.//g')

  if tmux ls 2>&1 | grep "$name"; then
    tmux attach -t "$name"
  elif [ -f .envrc ]; then
    direnv exec / tmux new-session -s "$name"
  else
    tmux new-session -s "$name"
  fi
}
