#!/bin/zsh

# swap capslock with escape
if test $(uname) = Linux && test ! -z "$DISPLAY"; then
	setxkbmap -option caps:swapescape
fi

# Environment
export COLORTERM=truecolor
export EDITOR=vi

# brew
if test $(uname) = "Darwin"; then
	eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# rust
. "$HOME/.cargo/env"

# prompt
eval "$(starship init zsh)"
