#!/bin/sh
set -e # fail on error


# Configuration
#################################################################################

# OS
OS=$(uname)

# Common directories
PERSONAL=$HOME/personal
WORK=$HOME/work
SRC=$HOME/src
BIN=$HOME/.bin

# Tool versions
GO_VERSION=1.22.3
RUST_TOOLCHAIN=nightly
NODE_VERSION=22.1.0


# Common functions
#################################################################################
info() {
	echo " > $1"
}


# Create common directories
#################################################################################
mkdir -p $PERSONAL $WORK $SRC $BIN
export PATH="$PATH:$BIN"


# Common utils
#################################################################################

# C compiler & make
if ! command -v cc >/dev/null; then
	test $OS = Linux && sudo apt install -y build-essential
fi


# Ninja
#################################################################################
if ! command -v ninja >/dev/null; then

	# source
	if test ! -d $SRC/ninja; then
		info "Cloning ninja"
		git clone https://github.com/ninja-build/ninja $SRC/ninja
	fi

	# build
	info "Installing ninja"
	cd $SRC/ninja
	./configure.py --bootstrap
	cp ninja $BIN/ninja
	cd -

	# test
	ninja --version
	info "Installed ninja"

fi


# Golang
# NOTE: We need to get binaries directly.
#       Because Go compiler is self-hosted.
#################################################################################
export PATH="$PATH:/usr/local/go/bin"
if ! command -v go >/dev/null; then

	# download
	case $OS in
		Darwin)
			GO_TARBALL="go$GO_VERSION.darwin-arm64.tar.gz"
			;;
		Linux)
			GO_TARBALL="go$GO_VERSION.linux-amd64.tar.gz"
			;;
	esac
	if test ! -f $GO_TARBALL; then
		info "Downloading Go"
		curl -LO "https://go.dev/dl/$GO_TARBALL"
	fi

	# install
	tar -xvf $GO_TARBALL
	sudo mv go /usr/local/go
	sudo chown -R $(whoami) /usr/local/go

	# check
	go version >/dev/null
	info "Installed Go"

	# clenaup
	rm $GO_TARBALL

fi


# Rust
# NOTE: We need to get binaries directly.
#       Because Rust compiler is self-hosted.
#################################################################################
export PATH="$PATH:$HOME/.cargo/bin"
if ! command -v cargo >/dev/null; then

	# installer (unattended)
	if test ! -d $HOME/.cargo; then
		info "Downloading Rust"
		curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
		| sh -s -- -y --no-modify-path --default-toolchain $RUST_TOOLCHAIN
	fi

	# check
	cargo --version >/dev/null
	info "Installed Rust"

fi

info "Installing cargo packages"
cargo install cargo-binstall
cargo binstall -y   \
	cargo-watch \
	bacon       \
	fd-find     \
	hyperfine
info "Installed cargo packages"


# Node
#################################################################################
if ! command -v node >/dev/null; then

	# source
	if test ! -d $SRC/node; then
		info "Cloning Node"
		git clone --depth=1 https://github.com/nodejs/node $SRC/node
	fi

	# build
	info "Installing Node"
	cd $SRC/node
	git fetch --tags
	git checkout "tags/v$NODE_VERSION"
	./configure --ninja && make
	sudo make install
	cd -

	# check
	node --version
	info "Installed Node"

fi


# Redis
#################################################################################
if ! command -v redis-server >/dev/null; then

	# source code
	info "Installing redis"
	test ! -f redis-stable.tar.gz && curl -LO https://download.redis.io/redis-stable.tar.gz

	tar -xzvf redis-stable.tar.gz
	cd redis-stable
	sudo make install
	cd -

	# check
	redis-server --version
	info "Installed redis"

	# cleanup
	rm redis-stable.tar.gz
	rm -rf redis-stable

fi


# entr
#################################################################################
if ! command -v entr >/dev/null; then

	# source code
	if test ! -d $SRC/entr; then
		info "Cloning entr"
		git clone --depth=1 https://github.com/eradman/entr $SRC/entr
	fi

	# build
	cd $SRC/entr
	./configure
	sudo make install
	cd -

	# check
	which entr >/dev/null

fi


# wrk
#################################################################################
if ! command -v wrk >/dev/null; then

	# source code
	if test ! -d $SRC/wrk; then
		info "Cloning wrk"
		git clone --depth=1 https://github.com/wg/wrk $SRC/wrk
	fi

	# build
	cd $SRC/wrk
	make
	cp $SRC/wrk/wrk $BIN
	cd -

	# check
	wrk --version >/dev/null

fi


# httpie
#################################################################################
if ! command -v http >/dev/null; then
	python3 -m pip install --upgrade pip wheel
	python3 -m pip install httpie
fi


# Symlink dotfiles
#################################################################################
ln -sf $(pwd)/dot_shrc  $HOME/.zshrc
ln -sf $(pwd)/dot_shrc  $HOME/.bashrc
ln -sf $(pwd)/dot_vimrc $HOME/.vimrc


# Done
#################################################################################
info "Done"
