#!/bin/sh
set -e # Stop on error

# nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash >/dev/null
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
nvm install node

# bazel
npm install -g @bazel/bazelisk

# kur
test ! -d $HOME/.cargo && brew install rustup && rustup -y
rustup component add rust-analyzer
command -v kur >/dev/null || cargo install kur
kur fmt
kur sync

# symlinks
symlnk() {
  if test -L $2; then
    return
  fi

  if test -d $2; then
    rm -rf $2
  fi

  ln -sf $1 $2
}

symlnk $(pwd)/dot_shrc $HOME/.zshrc
symlnk $(pwd)/dot_config $HOME/.config
symlnk $(pwd)/dot_vimrc $HOME/.vimrc
