#!/bin/sh
set -e # Stop on error

# Install shit
brew bundle --cleanup

# I believe one day the Rust toolchain
# will be superior to anything on the market.
# Until then, FML
test ! -d $HOME/.cargo && rustup -y
cargo install cargo-binstall
cargo binstall       \
      cargo-watch    \
      cargo-outdated \
      starship       \
      mdbook

# Node stuff
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
nvm install --lts

# Bazel
bazelisk

# Symlink dotfiles
symlnk() {
	if test -L $2
	then
		return
	fi

	if test -d $2
	then
		rm -rf $2
	fi

	ln -sf $1 $2
}

symlnk $(pwd)/dot_shrc   $HOME/.zshrc
symlnk $(pwd)/dot_config $HOME/.config
symlnk $(pwd)/dot_vimrc  $HOME/.vimrc
