#!/bin/zsh

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(find ~/work ~/personal -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux && echo $?)

tmux has-session -t=$selected_name 2>/dev/null ||
	tmux new-session -ds $selected_name -c $selected

if test -z "$TMUX"; then
	tmux attach -t $selected_name
else
	tmux switch-client -t $selected_name
fi
